version: "2"

run:
  timeout: 5m

linters:
  enable:
    - ineffassign
    - staticcheck
  disable:
    - errcheck
    - govet
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1005"
        - "-QF1003"
        - "-QF1008"
        - "-ST1000"
        - "-ST1003"
        - "-ST1021"