package provider

import "encoding/json"

// ChatCompletionResponse represents the API response for chat completions.
// It contains the generated response, model information, and usage statistics.
type ChatCompletionResponse struct {
	ID      string                 `json:"id"`      // Unique identifier for the completion
	Object  string                 `json:"object"`  // Type of object (e.g., "chat.completion")
	Created int                    `json:"created"` // Unix timestamp when the completion was created
	Model   string                 `json:"model"`   // Model used for the completion
	Choices []ChatCompletionChoice `json:"choices"` // List of possible completions
	Usage   ChatCompletionUsage    `json:"usage"`   // Token usage statistics
}

// ChatCompletionChoice represents a single completion option from the model.
// It contains the generated message and information about why the completion finished.
type ChatCompletionChoice struct {
	Index        int                   `json:"index"`         // Index of the choice in the list
	Message      ChatCompletionMessage `json:"message"`       // The generated message
	FinishReason string                `json:"finish_reason"` // Reason why the completion finished
}

// ChatCompletionMessage represents a message in the chat completion.
// It can be either a user message, assistant message, or system message.
type ChatCompletionMessage struct {
	Role         string            `json:"role"`                    // Role of the message sender (system, user, assistant)
	Content      string            `json:"content"`                 // Content of the message
	FunctionCall *ChatFunctionCall `json:"function_call,omitempty"` // Deprecated: Optional function call
	ToolCalls    []ChatToolCall    `json:"tool_calls,omitempty"`    // Optional tool calls
	Name         string            `json:"name,omitempty"`          // Optional name of the message sender
	ToolCallID   string            `json:"tool_call_id,omitempty"`  // Tool call ID for tool messages
}

// ChatToolCall represents a tool call generated by the model.
type ChatToolCall struct {
	ID       string           `json:"id"`
	Type     string           `json:"type"`
	Function ChatFunctionCall `json:"function"`
}

// ChatFunctionCall represents a function call generated by the model.
// It contains the function name and arguments to be passed to the function.
type ChatFunctionCall struct {
	Name      string `json:"name"`      // Name of the function to call
	Arguments string `json:"arguments"` // JSON string containing function arguments
}

// ChatCompletionUsage represents token usage statistics for the completion request.
// It tracks the number of tokens used in the prompt and completion.
type ChatCompletionUsage struct {
	PromptTokens     int `json:"prompt_tokens"`     // Number of tokens in the prompt
	CompletionTokens int `json:"completion_tokens"` // Number of tokens in the completion
	TotalTokens      int `json:"total_tokens"`      // Total number of tokens used
}

// ChatCompletionRequest represents the request payload for creating a chat completion.
// It specifies the model, messages, and various parameters to control the completion.
type ChatCompletionRequest struct {
	Model            string                  `json:"model"`                       // ID of the model to use
	Messages         []ChatCompletionMessage `json:"messages"`                    // List of messages in the conversation
	Functions        []ChatFunction          `json:"functions,omitempty"`         // Deprecated: Optional list of available functions
	FunctionCall     interface{}             `json:"function_call,omitempty"`     // Deprecated: Optional function call configuration
	Tools            []ChatTool              `json:"tools,omitempty"`             // List of available tools
	ToolChoice       interface{}             `json:"tool_choice,omitempty"`       // Control which tool is called
	Temperature      float64                 `json:"temperature,omitempty"`       // Sampling temperature
	TopP             float64                 `json:"top_p,omitempty"`             // Nucleus sampling parameter
	N                int                     `json:"n,omitempty"`                 // Number of completions to generate
	Stream           bool                    `json:"stream,omitempty"`            // Whether to stream the response
	Stop             []string                `json:"stop,omitempty"`              // Optional stop sequences
	MaxTokens        int                     `json:"max_tokens,omitempty"`        // Maximum tokens to generate
	PresencePenalty  float64                 `json:"presence_penalty,omitempty"`  // Presence penalty parameter
	FrequencyPenalty float64                 `json:"frequency_penalty,omitempty"` // Frequency penalty parameter
	LogitBias        map[string]float64      `json:"logit_bias,omitempty"`        // Optional token bias
	User             string                  `json:"user,omitempty"`              // Optional user identifier
	Store            bool                    `json:"store,omitempty"`             // Whether to store the completion
	Metadata         map[string]string       `json:"metadata,omitempty"`          // Optional metadata for filtering
}

// ChatFunction represents a function that can be called by the model.
// It contains the function name, description, and parameter schema.
type ChatFunction struct {
	Name        string          `json:"name"`                  // Name of the function
	Description string          `json:"description,omitempty"` // Optional function description
	Parameters  json.RawMessage `json:"parameters"`            // JSON schema for function parameters
}

// ChatTool represents a tool that can be used by the model.
type ChatTool struct {
	Type     string       `json:"type"`     // Type of tool (e.g. "function")
	Function ChatFunction `json:"function"` // Function definition
}
