name: Bump Version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate next version
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: false
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        run: |
          git tag ${{ steps.release_drafter.outputs.tag_name }}
          git push origin ${{ steps.release_drafter.outputs.tag_name }}
